name: Build and Push Docker

on:
  push:
    branches: [ master ]
  workflow_dispatch:
    
jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build and push Docker images
      uses: docker/build-push-action@v1.1.0
      with:
        registry: registry.mikolajjuda.dev
        repository: rakbook-old
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tags: latest
